// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.web.admin;

import dev.yangshengtang.domain.YstAnswer;
import dev.yangshengtang.service.YstAnswerService;
import dev.yangshengtang.service.YstQuestionService;
import dev.yangshengtang.service.YstUserService;
import dev.yangshengtang.web.admin.YstAnswerController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect YstAnswerController_Roo_Controller {
    
    @Autowired
    YstAnswerService YstAnswerController.ystAnswerService;
    
    @Autowired
    YstQuestionService YstAnswerController.ystQuestionService;
    
    @Autowired
    YstUserService YstAnswerController.ystUserService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String YstAnswerController.create(@Valid YstAnswer ystAnswer, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, ystAnswer);
            return "admin/answers/create";
        }
        uiModel.asMap().clear();
        ystAnswerService.saveYstAnswer(ystAnswer);
        return "redirect:/admin/answers/" + encodeUrlPathSegment(ystAnswer.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String YstAnswerController.createForm(Model uiModel) {
        populateEditForm(uiModel, new YstAnswer());
        return "admin/answers/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String YstAnswerController.show(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("ystanswer", ystAnswerService.findYstAnswer(id));
        uiModel.addAttribute("itemId", id);
        return "admin/answers/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String YstAnswerController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("ystanswers", ystAnswerService.findYstAnswerEntries(firstResult, sizeNo));
            float nrOfPages = (float) ystAnswerService.countAllYstAnswers() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("ystanswers", ystAnswerService.findAllYstAnswers());
        }
        return "admin/answers/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String YstAnswerController.update(@Valid YstAnswer ystAnswer, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, ystAnswer);
            return "admin/answers/update";
        }
        uiModel.asMap().clear();
        ystAnswerService.updateYstAnswer(ystAnswer);
        return "redirect:/admin/answers/" + encodeUrlPathSegment(ystAnswer.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String YstAnswerController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, ystAnswerService.findYstAnswer(id));
        return "admin/answers/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String YstAnswerController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        YstAnswer ystAnswer = ystAnswerService.findYstAnswer(id);
        ystAnswerService.deleteYstAnswer(ystAnswer);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/admin/answers";
    }
    
    void YstAnswerController.populateEditForm(Model uiModel, YstAnswer ystAnswer) {
        uiModel.addAttribute("ystAnswer", ystAnswer);
        uiModel.addAttribute("ystquestions", ystQuestionService.findAllYstQuestions());
        uiModel.addAttribute("ystusers", ystUserService.findAllYstUsers());
    }
    
    String YstAnswerController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
