// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.web.admin;

import dev.yangshengtang.domain.YstAnswer;
import dev.yangshengtang.domain.YstQuestion;
import dev.yangshengtang.domain.YstUser;
import dev.yangshengtang.web.admin.YstAnswerController;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

privileged aspect YstAnswerController_Roo_Controller_Finder {
    
    @RequestMapping(params = { "find=ByQuestion", "form" }, method = RequestMethod.GET)
    public String YstAnswerController.findYstAnswersByQuestionForm(Model uiModel) {
        uiModel.addAttribute("ystquestions", ystQuestionService.findAllYstQuestions());
        return "admin/answers/findYstAnswersByQuestion";
    }
    
    @RequestMapping(params = "find=ByQuestion", method = RequestMethod.GET)
    public String YstAnswerController.findYstAnswersByQuestion(@RequestParam("question") YstQuestion question, Model uiModel) {
        uiModel.addAttribute("ystanswers", YstAnswer.findYstAnswersByQuestion(question).getResultList());
        return "admin/answers/list";
    }
    
    @RequestMapping(params = { "find=ByUser", "form" }, method = RequestMethod.GET)
    public String YstAnswerController.findYstAnswersByUserForm(Model uiModel) {
        uiModel.addAttribute("ystusers", ystUserService.findAllYstUsers());
        return "admin/answers/findYstAnswersByUser";
    }
    
    @RequestMapping(params = "find=ByUser", method = RequestMethod.GET)
    public String YstAnswerController.findYstAnswersByUser(@RequestParam("user") YstUser user, Model uiModel) {
        uiModel.addAttribute("ystanswers", YstAnswer.findYstAnswersByUser(user).getResultList());
        return "admin/answers/list";
    }
    
}
