// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.web.admin;

import dev.yangshengtang.domain.YstCategory;
import dev.yangshengtang.domain.YstSymptom;
import dev.yangshengtang.service.YstCategoryService;
import dev.yangshengtang.service.YstMedicineService;
import dev.yangshengtang.service.YstPathogenesisService;
import dev.yangshengtang.service.YstQuestionService;
import dev.yangshengtang.service.YstUserCategoryService;
import dev.yangshengtang.web.admin.YstCategoryController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect YstCategoryController_Roo_Controller {
    
    @Autowired
    YstCategoryService YstCategoryController.ystCategoryService;
    
    @Autowired
    YstMedicineService YstCategoryController.ystMedicineService;
    
    @Autowired
    YstPathogenesisService YstCategoryController.ystPathogenesisService;
    
    @Autowired
    YstQuestionService YstCategoryController.ystQuestionService;
    
    @Autowired
    YstUserCategoryService YstCategoryController.ystUserCategoryService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String YstCategoryController.create(@Valid YstCategory ystCategory, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, ystCategory);
            return "admin/categorys/create";
        }
        uiModel.asMap().clear();
        ystCategoryService.saveYstCategory(ystCategory);
        return "redirect:/admin/categorys/" + encodeUrlPathSegment(ystCategory.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String YstCategoryController.createForm(Model uiModel) {
        populateEditForm(uiModel, new YstCategory());
        return "admin/categorys/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String YstCategoryController.show(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("ystcategory", ystCategoryService.findYstCategory(id));
        uiModel.addAttribute("itemId", id);
        return "admin/categorys/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String YstCategoryController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("ystcategorys", ystCategoryService.findYstCategoryEntries(firstResult, sizeNo));
            float nrOfPages = (float) ystCategoryService.countAllYstCategorys() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("ystcategorys", ystCategoryService.findAllYstCategorys());
        }
        return "admin/categorys/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String YstCategoryController.update(@Valid YstCategory ystCategory, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, ystCategory);
            return "admin/categorys/update";
        }
        uiModel.asMap().clear();
        ystCategoryService.updateYstCategory(ystCategory);
        return "redirect:/admin/categorys/" + encodeUrlPathSegment(ystCategory.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String YstCategoryController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, ystCategoryService.findYstCategory(id));
        return "admin/categorys/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String YstCategoryController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        YstCategory ystCategory = ystCategoryService.findYstCategory(id);
        ystCategoryService.deleteYstCategory(ystCategory);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/admin/categorys";
    }
    
    void YstCategoryController.populateEditForm(Model uiModel, YstCategory ystCategory) {
        uiModel.addAttribute("ystCategory", ystCategory);
        uiModel.addAttribute("ystmedicines", ystMedicineService.findAllYstMedicines());
        uiModel.addAttribute("ystpathogeneses", ystPathogenesisService.findAllYstPathogeneses());
        uiModel.addAttribute("ystquestions", ystQuestionService.findAllYstQuestions());
        uiModel.addAttribute("ystsymptoms", YstSymptom.findAllYstSymptoms());
        uiModel.addAttribute("ystusercategorys", ystUserCategoryService.findAllYstUserCategorys());
    }
    
    String YstCategoryController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
