// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.web.admin;

import dev.yangshengtang.domain.YstMedicineSymptom;
import dev.yangshengtang.domain.YstSymptom;
import dev.yangshengtang.service.YstMedicineService;
import dev.yangshengtang.service.YstMedicineSymptomService;
import dev.yangshengtang.web.admin.YstMedicineSymptomController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect YstMedicineSymptomController_Roo_Controller {
    
    @Autowired
    YstMedicineSymptomService YstMedicineSymptomController.ystMedicineSymptomService;
    
    @Autowired
    YstMedicineService YstMedicineSymptomController.ystMedicineService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String YstMedicineSymptomController.create(@Valid YstMedicineSymptom ystMedicineSymptom, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, ystMedicineSymptom);
            return "admin/medicinesymptoms/create";
        }
        uiModel.asMap().clear();
        ystMedicineSymptomService.saveYstMedicineSymptom(ystMedicineSymptom);
        return "redirect:/admin/medicinesymptoms/" + encodeUrlPathSegment(ystMedicineSymptom.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String YstMedicineSymptomController.createForm(Model uiModel) {
        populateEditForm(uiModel, new YstMedicineSymptom());
        return "admin/medicinesymptoms/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String YstMedicineSymptomController.show(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("ystmedicinesymptom", ystMedicineSymptomService.findYstMedicineSymptom(id));
        uiModel.addAttribute("itemId", id);
        return "admin/medicinesymptoms/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String YstMedicineSymptomController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("ystmedicinesymptoms", ystMedicineSymptomService.findYstMedicineSymptomEntries(firstResult, sizeNo));
            float nrOfPages = (float) ystMedicineSymptomService.countAllYstMedicineSymptoms() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("ystmedicinesymptoms", ystMedicineSymptomService.findAllYstMedicineSymptoms());
        }
        return "admin/medicinesymptoms/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String YstMedicineSymptomController.update(@Valid YstMedicineSymptom ystMedicineSymptom, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, ystMedicineSymptom);
            return "admin/medicinesymptoms/update";
        }
        uiModel.asMap().clear();
        ystMedicineSymptomService.updateYstMedicineSymptom(ystMedicineSymptom);
        return "redirect:/admin/medicinesymptoms/" + encodeUrlPathSegment(ystMedicineSymptom.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String YstMedicineSymptomController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, ystMedicineSymptomService.findYstMedicineSymptom(id));
        return "admin/medicinesymptoms/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String YstMedicineSymptomController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        YstMedicineSymptom ystMedicineSymptom = ystMedicineSymptomService.findYstMedicineSymptom(id);
        ystMedicineSymptomService.deleteYstMedicineSymptom(ystMedicineSymptom);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/admin/medicinesymptoms";
    }
    
    void YstMedicineSymptomController.populateEditForm(Model uiModel, YstMedicineSymptom ystMedicineSymptom) {
        uiModel.addAttribute("ystMedicineSymptom", ystMedicineSymptom);
        uiModel.addAttribute("ystmedicines", ystMedicineService.findAllYstMedicines());
        uiModel.addAttribute("ystsymptoms", YstSymptom.findAllYstSymptoms());
    }
    
    String YstMedicineSymptomController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
