// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.web.admin;

import dev.yangshengtang.domain.YstMedicine;
import dev.yangshengtang.service.YstCategoryService;
import dev.yangshengtang.service.YstMedicineService;
import dev.yangshengtang.service.YstMedicineSymptomService;
import dev.yangshengtang.web.admin.YstMedicineController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect YstMedicineController_Roo_Controller {
    
    @Autowired
    YstMedicineService YstMedicineController.ystMedicineService;
    
    @Autowired
    YstCategoryService YstMedicineController.ystCategoryService;
    
    @Autowired
    YstMedicineSymptomService YstMedicineController.ystMedicineSymptomService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String YstMedicineController.create(@Valid YstMedicine ystMedicine, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, ystMedicine);
            return "admin/medicines/create";
        }
        uiModel.asMap().clear();
        ystMedicineService.saveYstMedicine(ystMedicine);
        return "redirect:/admin/medicines/" + encodeUrlPathSegment(ystMedicine.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String YstMedicineController.createForm(Model uiModel) {
        populateEditForm(uiModel, new YstMedicine());
        return "admin/medicines/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String YstMedicineController.show(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("ystmedicine", ystMedicineService.findYstMedicine(id));
        uiModel.addAttribute("itemId", id);
        return "admin/medicines/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String YstMedicineController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("ystmedicines", ystMedicineService.findYstMedicineEntries(firstResult, sizeNo));
            float nrOfPages = (float) ystMedicineService.countAllYstMedicines() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("ystmedicines", ystMedicineService.findAllYstMedicines());
        }
        return "admin/medicines/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String YstMedicineController.update(@Valid YstMedicine ystMedicine, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, ystMedicine);
            return "admin/medicines/update";
        }
        uiModel.asMap().clear();
        ystMedicineService.updateYstMedicine(ystMedicine);
        return "redirect:/admin/medicines/" + encodeUrlPathSegment(ystMedicine.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String YstMedicineController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, ystMedicineService.findYstMedicine(id));
        return "admin/medicines/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String YstMedicineController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        YstMedicine ystMedicine = ystMedicineService.findYstMedicine(id);
        ystMedicineService.deleteYstMedicine(ystMedicine);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/admin/medicines";
    }
    
    void YstMedicineController.populateEditForm(Model uiModel, YstMedicine ystMedicine) {
        uiModel.addAttribute("ystMedicine", ystMedicine);
        uiModel.addAttribute("ystcategorys", ystCategoryService.findAllYstCategorys());
        uiModel.addAttribute("ystmedicinesymptoms", ystMedicineSymptomService.findAllYstMedicineSymptoms());
    }
    
    String YstMedicineController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
