// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.web.admin;

import dev.yangshengtang.domain.YstPathogenesis;
import dev.yangshengtang.service.YstCategoryService;
import dev.yangshengtang.service.YstPathogenesisService;
import dev.yangshengtang.web.admin.YstPathogenesisController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect YstPathogenesisController_Roo_Controller {
    
    @Autowired
    YstPathogenesisService YstPathogenesisController.ystPathogenesisService;
    
    @Autowired
    YstCategoryService YstPathogenesisController.ystCategoryService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String YstPathogenesisController.create(@Valid YstPathogenesis ystPathogenesis, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, ystPathogenesis);
            return "admin/pathogeneses/create";
        }
        uiModel.asMap().clear();
        ystPathogenesisService.saveYstPathogenesis(ystPathogenesis);
        return "redirect:/admin/pathogeneses/" + encodeUrlPathSegment(ystPathogenesis.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String YstPathogenesisController.createForm(Model uiModel) {
        populateEditForm(uiModel, new YstPathogenesis());
        return "admin/pathogeneses/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String YstPathogenesisController.show(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("ystpathogenesis", ystPathogenesisService.findYstPathogenesis(id));
        uiModel.addAttribute("itemId", id);
        return "admin/pathogeneses/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String YstPathogenesisController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("ystpathogeneses", ystPathogenesisService.findYstPathogenesisEntries(firstResult, sizeNo));
            float nrOfPages = (float) ystPathogenesisService.countAllYstPathogeneses() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("ystpathogeneses", ystPathogenesisService.findAllYstPathogeneses());
        }
        return "admin/pathogeneses/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String YstPathogenesisController.update(@Valid YstPathogenesis ystPathogenesis, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, ystPathogenesis);
            return "admin/pathogeneses/update";
        }
        uiModel.asMap().clear();
        ystPathogenesisService.updateYstPathogenesis(ystPathogenesis);
        return "redirect:/admin/pathogeneses/" + encodeUrlPathSegment(ystPathogenesis.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String YstPathogenesisController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, ystPathogenesisService.findYstPathogenesis(id));
        return "admin/pathogeneses/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String YstPathogenesisController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        YstPathogenesis ystPathogenesis = ystPathogenesisService.findYstPathogenesis(id);
        ystPathogenesisService.deleteYstPathogenesis(ystPathogenesis);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/admin/pathogeneses";
    }
    
    void YstPathogenesisController.populateEditForm(Model uiModel, YstPathogenesis ystPathogenesis) {
        uiModel.addAttribute("ystPathogenesis", ystPathogenesis);
        uiModel.addAttribute("ystcategorys", ystCategoryService.findAllYstCategorys());
    }
    
    String YstPathogenesisController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
