// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.web.admin;

import dev.yangshengtang.domain.YstCategory;
import dev.yangshengtang.domain.YstPathogenesis;
import dev.yangshengtang.web.admin.YstPathogenesisController;
import java.util.List;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

privileged aspect YstPathogenesisController_Roo_Controller_Json {
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET, headers = "Accept=application/json")
    @ResponseBody
    public ResponseEntity<String> YstPathogenesisController.showJson(@PathVariable("id") Integer id) {
        YstPathogenesis ystPathogenesis = ystPathogenesisService.findYstPathogenesis(id);
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json; charset=utf-8");
        if (ystPathogenesis == null) {
            return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
        }
        return new ResponseEntity<String>(ystPathogenesis.toJson(), headers, HttpStatus.OK);
    }
    
    @RequestMapping(headers = "Accept=application/json")
    @ResponseBody
    public ResponseEntity<String> YstPathogenesisController.listJson() {
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json; charset=utf-8");
        List<YstPathogenesis> result = ystPathogenesisService.findAllYstPathogeneses();
        return new ResponseEntity<String>(YstPathogenesis.toJsonArray(result), headers, HttpStatus.OK);
    }
    
    @RequestMapping(method = RequestMethod.POST, headers = "Accept=application/json")
    public ResponseEntity<String> YstPathogenesisController.createFromJson(@RequestBody String json) {
        YstPathogenesis ystPathogenesis = YstPathogenesis.fromJsonToYstPathogenesis(json);
        ystPathogenesisService.saveYstPathogenesis(ystPathogenesis);
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        return new ResponseEntity<String>(headers, HttpStatus.CREATED);
    }
    
    @RequestMapping(value = "/jsonArray", method = RequestMethod.POST, headers = "Accept=application/json")
    public ResponseEntity<String> YstPathogenesisController.createFromJsonArray(@RequestBody String json) {
        for (YstPathogenesis ystPathogenesis: YstPathogenesis.fromJsonArrayToYstPathogeneses(json)) {
            ystPathogenesisService.saveYstPathogenesis(ystPathogenesis);
        }
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        return new ResponseEntity<String>(headers, HttpStatus.CREATED);
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.PUT, headers = "Accept=application/json")
    public ResponseEntity<String> YstPathogenesisController.updateFromJson(@RequestBody String json, @PathVariable("id") Integer id) {
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        YstPathogenesis ystPathogenesis = YstPathogenesis.fromJsonToYstPathogenesis(json);
        if (ystPathogenesisService.updateYstPathogenesis(ystPathogenesis) == null) {
            return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
        }
        return new ResponseEntity<String>(headers, HttpStatus.OK);
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, headers = "Accept=application/json")
    public ResponseEntity<String> YstPathogenesisController.deleteFromJson(@PathVariable("id") Integer id) {
        YstPathogenesis ystPathogenesis = ystPathogenesisService.findYstPathogenesis(id);
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        if (ystPathogenesis == null) {
            return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
        }
        ystPathogenesisService.deleteYstPathogenesis(ystPathogenesis);
        return new ResponseEntity<String>(headers, HttpStatus.OK);
    }
    
    @RequestMapping(params = "find=ByCategory", headers = "Accept=application/json")
    @ResponseBody
    public ResponseEntity<String> YstPathogenesisController.jsonFindYstPathogenesesByCategory(@RequestParam("category") YstCategory category) {
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json; charset=utf-8");
        return new ResponseEntity<String>(YstPathogenesis.toJsonArray(YstPathogenesis.findYstPathogenesesByCategory(category).getResultList()), headers, HttpStatus.OK);
    }
    
}
