// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.web.admin;

import dev.yangshengtang.domain.YstCategory;
import dev.yangshengtang.domain.YstQuestion;
import dev.yangshengtang.web.admin.YstQuestionController;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

privileged aspect YstQuestionController_Roo_Controller_Finder {
    
    @RequestMapping(params = { "find=ByCategory", "form" }, method = RequestMethod.GET)
    public String YstQuestionController.findYstQuestionsByCategoryForm(Model uiModel) {
        uiModel.addAttribute("ystcategorys", ystCategoryService.findAllYstCategorys());
        return "admin/questions/findYstQuestionsByCategory";
    }
    
    @RequestMapping(params = "find=ByCategory", method = RequestMethod.GET)
    public String YstQuestionController.findYstQuestionsByCategory(@RequestParam("category") YstCategory category, Model uiModel) {
        uiModel.addAttribute("ystquestions", YstQuestion.findYstQuestionsByCategory(category).getResultList());
        return "admin/questions/list";
    }
    
}
