// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.web.admin;

import dev.yangshengtang.domain.YstUserCategory;
import dev.yangshengtang.web.admin.YstUserCategoryController;
import java.util.List;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

privileged aspect YstUserCategoryController_Roo_Controller_Json {
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET, headers = "Accept=application/json")
    @ResponseBody
    public ResponseEntity<String> YstUserCategoryController.showJson(@PathVariable("id") Integer id) {
        YstUserCategory ystUserCategory = ystUserCategoryService.findYstUserCategory(id);
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json; charset=utf-8");
        if (ystUserCategory == null) {
            return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
        }
        return new ResponseEntity<String>(ystUserCategory.toJson(), headers, HttpStatus.OK);
    }
    
    @RequestMapping(headers = "Accept=application/json")
    @ResponseBody
    public ResponseEntity<String> YstUserCategoryController.listJson() {
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json; charset=utf-8");
        List<YstUserCategory> result = ystUserCategoryService.findAllYstUserCategorys();
        return new ResponseEntity<String>(YstUserCategory.toJsonArray(result), headers, HttpStatus.OK);
    }
    
    @RequestMapping(method = RequestMethod.POST, headers = "Accept=application/json")
    public ResponseEntity<String> YstUserCategoryController.createFromJson(@RequestBody String json) {
        YstUserCategory ystUserCategory = YstUserCategory.fromJsonToYstUserCategory(json);
        ystUserCategoryService.saveYstUserCategory(ystUserCategory);
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        return new ResponseEntity<String>(headers, HttpStatus.CREATED);
    }
    
    @RequestMapping(value = "/jsonArray", method = RequestMethod.POST, headers = "Accept=application/json")
    public ResponseEntity<String> YstUserCategoryController.createFromJsonArray(@RequestBody String json) {
        for (YstUserCategory ystUserCategory: YstUserCategory.fromJsonArrayToYstUserCategorys(json)) {
            ystUserCategoryService.saveYstUserCategory(ystUserCategory);
        }
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        return new ResponseEntity<String>(headers, HttpStatus.CREATED);
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.PUT, headers = "Accept=application/json")
    public ResponseEntity<String> YstUserCategoryController.updateFromJson(@RequestBody String json, @PathVariable("id") Integer id) {
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        YstUserCategory ystUserCategory = YstUserCategory.fromJsonToYstUserCategory(json);
        if (ystUserCategoryService.updateYstUserCategory(ystUserCategory) == null) {
            return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
        }
        return new ResponseEntity<String>(headers, HttpStatus.OK);
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, headers = "Accept=application/json")
    public ResponseEntity<String> YstUserCategoryController.deleteFromJson(@PathVariable("id") Integer id) {
        YstUserCategory ystUserCategory = ystUserCategoryService.findYstUserCategory(id);
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        if (ystUserCategory == null) {
            return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
        }
        ystUserCategoryService.deleteYstUserCategory(ystUserCategory);
        return new ResponseEntity<String>(headers, HttpStatus.OK);
    }
    
}
