// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.web.admin;

import dev.yangshengtang.domain.YstUserCategory;
import dev.yangshengtang.service.YstCategoryService;
import dev.yangshengtang.service.YstUserCategoryService;
import dev.yangshengtang.service.YstUserService;
import dev.yangshengtang.web.admin.YstUserCategoryController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect YstUserCategoryController_Roo_Controller {
    
    @Autowired
    YstUserCategoryService YstUserCategoryController.ystUserCategoryService;
    
    @Autowired
    YstCategoryService YstUserCategoryController.ystCategoryService;
    
    @Autowired
    YstUserService YstUserCategoryController.ystUserService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String YstUserCategoryController.create(@Valid YstUserCategory ystUserCategory, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, ystUserCategory);
            return "admin/usercategorys/create";
        }
        uiModel.asMap().clear();
        ystUserCategoryService.saveYstUserCategory(ystUserCategory);
        return "redirect:/admin/usercategorys/" + encodeUrlPathSegment(ystUserCategory.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String YstUserCategoryController.createForm(Model uiModel) {
        populateEditForm(uiModel, new YstUserCategory());
        return "admin/usercategorys/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String YstUserCategoryController.show(@PathVariable("id") Integer id, Model uiModel) {
        uiModel.addAttribute("ystusercategory", ystUserCategoryService.findYstUserCategory(id));
        uiModel.addAttribute("itemId", id);
        return "admin/usercategorys/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String YstUserCategoryController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("ystusercategorys", ystUserCategoryService.findYstUserCategoryEntries(firstResult, sizeNo));
            float nrOfPages = (float) ystUserCategoryService.countAllYstUserCategorys() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("ystusercategorys", ystUserCategoryService.findAllYstUserCategorys());
        }
        return "admin/usercategorys/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String YstUserCategoryController.update(@Valid YstUserCategory ystUserCategory, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, ystUserCategory);
            return "admin/usercategorys/update";
        }
        uiModel.asMap().clear();
        ystUserCategoryService.updateYstUserCategory(ystUserCategory);
        return "redirect:/admin/usercategorys/" + encodeUrlPathSegment(ystUserCategory.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String YstUserCategoryController.updateForm(@PathVariable("id") Integer id, Model uiModel) {
        populateEditForm(uiModel, ystUserCategoryService.findYstUserCategory(id));
        return "admin/usercategorys/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String YstUserCategoryController.delete(@PathVariable("id") Integer id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        YstUserCategory ystUserCategory = ystUserCategoryService.findYstUserCategory(id);
        ystUserCategoryService.deleteYstUserCategory(ystUserCategory);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/admin/usercategorys";
    }
    
    void YstUserCategoryController.populateEditForm(Model uiModel, YstUserCategory ystUserCategory) {
        uiModel.addAttribute("ystUserCategory", ystUserCategory);
        uiModel.addAttribute("ystcategorys", ystCategoryService.findAllYstCategorys());
        uiModel.addAttribute("ystusers", ystUserService.findAllYstUsers());
    }
    
    String YstUserCategoryController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
