// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.service;

import dev.yangshengtang.domain.YstAccount;
import dev.yangshengtang.repository.YstAccountRepository;
import dev.yangshengtang.service.YstAccountServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect YstAccountServiceImpl_Roo_Service {
    
    declare @type: YstAccountServiceImpl: @Service;
    
    declare @type: YstAccountServiceImpl: @Transactional;
    
    @Autowired
    YstAccountRepository YstAccountServiceImpl.ystAccountRepository;
    
    public long YstAccountServiceImpl.countAllYstAccounts() {
        return ystAccountRepository.count();
    }
    
    public void YstAccountServiceImpl.deleteYstAccount(YstAccount ystAccount) {
        ystAccountRepository.delete(ystAccount);
    }
    
    public YstAccount YstAccountServiceImpl.findYstAccount(Integer id) {
        return ystAccountRepository.findOne(id);
    }
    
    public List<YstAccount> YstAccountServiceImpl.findAllYstAccounts() {
        return ystAccountRepository.findAll();
    }
    
    public List<YstAccount> YstAccountServiceImpl.findYstAccountEntries(int firstResult, int maxResults) {
        return ystAccountRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void YstAccountServiceImpl.saveYstAccount(YstAccount ystAccount) {
        ystAccountRepository.save(ystAccount);
    }
    
    public YstAccount YstAccountServiceImpl.updateYstAccount(YstAccount ystAccount) {
        return ystAccountRepository.save(ystAccount);
    }
    
}
