// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.service;

import dev.yangshengtang.domain.YstAnswer;
import dev.yangshengtang.service.YstAnswerService;
import java.util.List;

privileged aspect YstAnswerService_Roo_Service {
    
    public abstract long YstAnswerService.countAllYstAnswers();    
    public abstract void YstAnswerService.deleteYstAnswer(YstAnswer ystAnswer);    
    public abstract YstAnswer YstAnswerService.findYstAnswer(Integer id);    
    public abstract List<YstAnswer> YstAnswerService.findAllYstAnswers();    
    public abstract List<YstAnswer> YstAnswerService.findYstAnswerEntries(int firstResult, int maxResults);    
    public abstract void YstAnswerService.saveYstAnswer(YstAnswer ystAnswer);    
    public abstract YstAnswer YstAnswerService.updateYstAnswer(YstAnswer ystAnswer);    
}
