// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.service;

import dev.yangshengtang.domain.YstCategory;
import dev.yangshengtang.service.YstCategoryService;
import java.util.List;

privileged aspect YstCategoryService_Roo_Service {
    
    public abstract long YstCategoryService.countAllYstCategorys();    
    public abstract void YstCategoryService.deleteYstCategory(YstCategory ystCategory);    
    public abstract YstCategory YstCategoryService.findYstCategory(Integer id);    
    public abstract List<YstCategory> YstCategoryService.findAllYstCategorys();    
    public abstract List<YstCategory> YstCategoryService.findYstCategoryEntries(int firstResult, int maxResults);    
    public abstract void YstCategoryService.saveYstCategory(YstCategory ystCategory);    
    public abstract YstCategory YstCategoryService.updateYstCategory(YstCategory ystCategory);    
}
