// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.service;

import dev.yangshengtang.domain.YstMedicine;
import dev.yangshengtang.repository.YstMedicineRepository;
import dev.yangshengtang.service.YstMedicineServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect YstMedicineServiceImpl_Roo_Service {
    
    declare @type: YstMedicineServiceImpl: @Service;
    
    declare @type: YstMedicineServiceImpl: @Transactional;
    
    @Autowired
    YstMedicineRepository YstMedicineServiceImpl.ystMedicineRepository;
    
    public long YstMedicineServiceImpl.countAllYstMedicines() {
        return ystMedicineRepository.count();
    }
    
    public void YstMedicineServiceImpl.deleteYstMedicine(YstMedicine ystMedicine) {
        ystMedicineRepository.delete(ystMedicine);
    }
    
    public YstMedicine YstMedicineServiceImpl.findYstMedicine(Integer id) {
        return ystMedicineRepository.findOne(id);
    }
    
    public List<YstMedicine> YstMedicineServiceImpl.findAllYstMedicines() {
        return ystMedicineRepository.findAll();
    }
    
    public List<YstMedicine> YstMedicineServiceImpl.findYstMedicineEntries(int firstResult, int maxResults) {
        return ystMedicineRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void YstMedicineServiceImpl.saveYstMedicine(YstMedicine ystMedicine) {
        ystMedicineRepository.save(ystMedicine);
    }
    
    public YstMedicine YstMedicineServiceImpl.updateYstMedicine(YstMedicine ystMedicine) {
        return ystMedicineRepository.save(ystMedicine);
    }
    
}
