// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.service;

import dev.yangshengtang.domain.YstMedicineSymptom;
import dev.yangshengtang.repository.YstMedicineSymptomRepository;
import dev.yangshengtang.service.YstMedicineSymptomServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect YstMedicineSymptomServiceImpl_Roo_Service {
    
    declare @type: YstMedicineSymptomServiceImpl: @Service;
    
    declare @type: YstMedicineSymptomServiceImpl: @Transactional;
    
    @Autowired
    YstMedicineSymptomRepository YstMedicineSymptomServiceImpl.ystMedicineSymptomRepository;
    
    public long YstMedicineSymptomServiceImpl.countAllYstMedicineSymptoms() {
        return ystMedicineSymptomRepository.count();
    }
    
    public void YstMedicineSymptomServiceImpl.deleteYstMedicineSymptom(YstMedicineSymptom ystMedicineSymptom) {
        ystMedicineSymptomRepository.delete(ystMedicineSymptom);
    }
    
    public YstMedicineSymptom YstMedicineSymptomServiceImpl.findYstMedicineSymptom(Integer id) {
        return ystMedicineSymptomRepository.findOne(id);
    }
    
    public List<YstMedicineSymptom> YstMedicineSymptomServiceImpl.findAllYstMedicineSymptoms() {
        return ystMedicineSymptomRepository.findAll();
    }
    
    public List<YstMedicineSymptom> YstMedicineSymptomServiceImpl.findYstMedicineSymptomEntries(int firstResult, int maxResults) {
        return ystMedicineSymptomRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void YstMedicineSymptomServiceImpl.saveYstMedicineSymptom(YstMedicineSymptom ystMedicineSymptom) {
        ystMedicineSymptomRepository.save(ystMedicineSymptom);
    }
    
    public YstMedicineSymptom YstMedicineSymptomServiceImpl.updateYstMedicineSymptom(YstMedicineSymptom ystMedicineSymptom) {
        return ystMedicineSymptomRepository.save(ystMedicineSymptom);
    }
    
}
