// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.service;

import dev.yangshengtang.domain.YstMedicine;
import dev.yangshengtang.service.YstMedicineService;
import java.util.List;

privileged aspect YstMedicineService_Roo_Service {
    
    public abstract long YstMedicineService.countAllYstMedicines();    
    public abstract void YstMedicineService.deleteYstMedicine(YstMedicine ystMedicine);    
    public abstract YstMedicine YstMedicineService.findYstMedicine(Integer id);    
    public abstract List<YstMedicine> YstMedicineService.findAllYstMedicines();    
    public abstract List<YstMedicine> YstMedicineService.findYstMedicineEntries(int firstResult, int maxResults);    
    public abstract void YstMedicineService.saveYstMedicine(YstMedicine ystMedicine);    
    public abstract YstMedicine YstMedicineService.updateYstMedicine(YstMedicine ystMedicine);    
}
