// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.service;

import dev.yangshengtang.domain.YstMedicineSymptom;
import dev.yangshengtang.service.YstMedicineSymptomService;
import java.util.List;

privileged aspect YstMedicineSymptomService_Roo_Service {
    
    public abstract long YstMedicineSymptomService.countAllYstMedicineSymptoms();    
    public abstract void YstMedicineSymptomService.deleteYstMedicineSymptom(YstMedicineSymptom ystMedicineSymptom);    
    public abstract YstMedicineSymptom YstMedicineSymptomService.findYstMedicineSymptom(Integer id);    
    public abstract List<YstMedicineSymptom> YstMedicineSymptomService.findAllYstMedicineSymptoms();    
    public abstract List<YstMedicineSymptom> YstMedicineSymptomService.findYstMedicineSymptomEntries(int firstResult, int maxResults);    
    public abstract void YstMedicineSymptomService.saveYstMedicineSymptom(YstMedicineSymptom ystMedicineSymptom);    
    public abstract YstMedicineSymptom YstMedicineSymptomService.updateYstMedicineSymptom(YstMedicineSymptom ystMedicineSymptom);    
}
