// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.service;

import dev.yangshengtang.domain.YstPathogenesis;
import dev.yangshengtang.service.YstPathogenesisService;
import java.util.List;

privileged aspect YstPathogenesisService_Roo_Service {
    
    public abstract long YstPathogenesisService.countAllYstPathogeneses();    
    public abstract void YstPathogenesisService.deleteYstPathogenesis(YstPathogenesis ystPathogenesis);    
    public abstract YstPathogenesis YstPathogenesisService.findYstPathogenesis(Integer id);    
    public abstract List<YstPathogenesis> YstPathogenesisService.findAllYstPathogeneses();    
    public abstract List<YstPathogenesis> YstPathogenesisService.findYstPathogenesisEntries(int firstResult, int maxResults);    
    public abstract void YstPathogenesisService.saveYstPathogenesis(YstPathogenesis ystPathogenesis);    
    public abstract YstPathogenesis YstPathogenesisService.updateYstPathogenesis(YstPathogenesis ystPathogenesis);    
}
