// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.service;

import dev.yangshengtang.domain.YstQuestion;
import dev.yangshengtang.repository.YstQuestionRepository;
import dev.yangshengtang.service.YstQuestionServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect YstQuestionServiceImpl_Roo_Service {
    
    declare @type: YstQuestionServiceImpl: @Service;
    
    declare @type: YstQuestionServiceImpl: @Transactional;
    
    @Autowired
    YstQuestionRepository YstQuestionServiceImpl.ystQuestionRepository;
    
    public long YstQuestionServiceImpl.countAllYstQuestions() {
        return ystQuestionRepository.count();
    }
    
    public void YstQuestionServiceImpl.deleteYstQuestion(YstQuestion ystQuestion) {
        ystQuestionRepository.delete(ystQuestion);
    }
    
    public YstQuestion YstQuestionServiceImpl.findYstQuestion(Integer id) {
        return ystQuestionRepository.findOne(id);
    }
    
    public List<YstQuestion> YstQuestionServiceImpl.findAllYstQuestions() {
        return ystQuestionRepository.findAll();
    }
    
    public List<YstQuestion> YstQuestionServiceImpl.findYstQuestionEntries(int firstResult, int maxResults) {
        return ystQuestionRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void YstQuestionServiceImpl.saveYstQuestion(YstQuestion ystQuestion) {
        ystQuestionRepository.save(ystQuestion);
    }
    
    public YstQuestion YstQuestionServiceImpl.updateYstQuestion(YstQuestion ystQuestion) {
        return ystQuestionRepository.save(ystQuestion);
    }
    
}
