// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.service;

import dev.yangshengtang.domain.YstUser;
import dev.yangshengtang.repository.YstUserRepository;
import dev.yangshengtang.service.YstUserServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect YstUserServiceImpl_Roo_Service {
    
    declare @type: YstUserServiceImpl: @Service;
    
    declare @type: YstUserServiceImpl: @Transactional;
    
    @Autowired
    YstUserRepository YstUserServiceImpl.ystUserRepository;
    
    public long YstUserServiceImpl.countAllYstUsers() {
        return ystUserRepository.count();
    }
    
    public void YstUserServiceImpl.deleteYstUser(YstUser ystUser) {
        ystUserRepository.delete(ystUser);
    }
    
    public YstUser YstUserServiceImpl.findYstUser(Integer id) {
        return ystUserRepository.findOne(id);
    }
    
    public List<YstUser> YstUserServiceImpl.findAllYstUsers() {
        return ystUserRepository.findAll();
    }
    
    public List<YstUser> YstUserServiceImpl.findYstUserEntries(int firstResult, int maxResults) {
        return ystUserRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void YstUserServiceImpl.saveYstUser(YstUser ystUser) {
        ystUserRepository.save(ystUser);
    }
    
    public YstUser YstUserServiceImpl.updateYstUser(YstUser ystUser) {
        return ystUserRepository.save(ystUser);
    }
    
}
