// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.service;

import dev.yangshengtang.domain.YstUserCategory;
import dev.yangshengtang.repository.YstUserCategoryRepository;
import dev.yangshengtang.service.YstUserCategoryServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect YstUserCategoryServiceImpl_Roo_Service {
    
    declare @type: YstUserCategoryServiceImpl: @Service;
    
    declare @type: YstUserCategoryServiceImpl: @Transactional;
    
    @Autowired
    YstUserCategoryRepository YstUserCategoryServiceImpl.ystUserCategoryRepository;
    
    public long YstUserCategoryServiceImpl.countAllYstUserCategorys() {
        return ystUserCategoryRepository.count();
    }
    
    public void YstUserCategoryServiceImpl.deleteYstUserCategory(YstUserCategory ystUserCategory) {
        ystUserCategoryRepository.delete(ystUserCategory);
    }
    
    public YstUserCategory YstUserCategoryServiceImpl.findYstUserCategory(Integer id) {
        return ystUserCategoryRepository.findOne(id);
    }
    
    public List<YstUserCategory> YstUserCategoryServiceImpl.findAllYstUserCategorys() {
        return ystUserCategoryRepository.findAll();
    }
    
    public List<YstUserCategory> YstUserCategoryServiceImpl.findYstUserCategoryEntries(int firstResult, int maxResults) {
        return ystUserCategoryRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void YstUserCategoryServiceImpl.saveYstUserCategory(YstUserCategory ystUserCategory) {
        ystUserCategoryRepository.save(ystUserCategory);
    }
    
    public YstUserCategory YstUserCategoryServiceImpl.updateYstUserCategory(YstUserCategory ystUserCategory) {
        return ystUserCategoryRepository.save(ystUserCategory);
    }
    
}
