// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.service;

import dev.yangshengtang.domain.YstUser;
import dev.yangshengtang.service.YstUserService;
import java.util.List;

privileged aspect YstUserService_Roo_Service {
    
    public abstract long YstUserService.countAllYstUsers();    
    public abstract void YstUserService.deleteYstUser(YstUser ystUser);    
    public abstract YstUser YstUserService.findYstUser(Integer id);    
    public abstract List<YstUser> YstUserService.findAllYstUsers();    
    public abstract List<YstUser> YstUserService.findYstUserEntries(int firstResult, int maxResults);    
    public abstract void YstUserService.saveYstUser(YstUser ystUser);    
    public abstract YstUser YstUserService.updateYstUser(YstUser ystUser);    
}
