// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.repository;

import dev.yangshengtang.domain.YstAccount;
import dev.yangshengtang.repository.YstAccountRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect YstAccountRepository_Roo_Jpa_Repository {
    
    declare parents: YstAccountRepository extends JpaRepository<YstAccount, Integer>;
    
    declare parents: YstAccountRepository extends JpaSpecificationExecutor<YstAccount>;
    
    declare @type: YstAccountRepository: @Repository;
    
}
