// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.repository;

import dev.yangshengtang.domain.YstCategory;
import dev.yangshengtang.repository.YstCategoryRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect YstCategoryRepository_Roo_Jpa_Repository {
    
    declare parents: YstCategoryRepository extends JpaRepository<YstCategory, Integer>;
    
    declare parents: YstCategoryRepository extends JpaSpecificationExecutor<YstCategory>;
    
    declare @type: YstCategoryRepository: @Repository;
    
}
