// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.repository;

import dev.yangshengtang.domain.YstMedicineSymptom;
import dev.yangshengtang.repository.YstMedicineSymptomRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect YstMedicineSymptomRepository_Roo_Jpa_Repository {
    
    declare parents: YstMedicineSymptomRepository extends JpaRepository<YstMedicineSymptom, Integer>;
    
    declare parents: YstMedicineSymptomRepository extends JpaSpecificationExecutor<YstMedicineSymptom>;
    
    declare @type: YstMedicineSymptomRepository: @Repository;
    
}
