// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.repository;

import dev.yangshengtang.domain.YstPathogenesis;
import dev.yangshengtang.repository.YstPathogenesisRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect YstPathogenesisRepository_Roo_Jpa_Repository {
    
    declare parents: YstPathogenesisRepository extends JpaRepository<YstPathogenesis, Integer>;
    
    declare parents: YstPathogenesisRepository extends JpaSpecificationExecutor<YstPathogenesis>;
    
    declare @type: YstPathogenesisRepository: @Repository;
    
}
