// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.repository;

import dev.yangshengtang.domain.YstQuestion;
import dev.yangshengtang.repository.YstQuestionRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect YstQuestionRepository_Roo_Jpa_Repository {
    
    declare parents: YstQuestionRepository extends JpaRepository<YstQuestion, Integer>;
    
    declare parents: YstQuestionRepository extends JpaSpecificationExecutor<YstQuestion>;
    
    declare @type: YstQuestionRepository: @Repository;
    
}
