// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.repository;

import dev.yangshengtang.domain.YstUser;
import dev.yangshengtang.repository.YstUserRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect YstUserRepository_Roo_Jpa_Repository {
    
    declare parents: YstUserRepository extends JpaRepository<YstUser, Integer>;
    
    declare parents: YstUserRepository extends JpaSpecificationExecutor<YstUser>;
    
    declare @type: YstUserRepository: @Repository;
    
}
