// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.repository;

import dev.yangshengtang.domain.YstUserCategory;
import dev.yangshengtang.repository.YstUserCategoryRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect YstUserCategoryRepository_Roo_Jpa_Repository {
    
    declare parents: YstUserCategoryRepository extends JpaRepository<YstUserCategory, Integer>;
    
    declare parents: YstUserCategoryRepository extends JpaSpecificationExecutor<YstUserCategory>;
    
    declare @type: YstUserCategoryRepository: @Repository;
    
}
