// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstAnswer;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect YstAnswer_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager YstAnswer.entityManager;
    
    public static final EntityManager YstAnswer.entityManager() {
        EntityManager em = new YstAnswer().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long YstAnswer.countYstAnswers() {
        return entityManager().createQuery("SELECT COUNT(o) FROM YstAnswer o", Long.class).getSingleResult();
    }
    
    public static List<YstAnswer> YstAnswer.findAllYstAnswers() {
        return entityManager().createQuery("SELECT o FROM YstAnswer o", YstAnswer.class).getResultList();
    }
    
    public static YstAnswer YstAnswer.findYstAnswer(Integer id) {
        if (id == null) return null;
        return entityManager().find(YstAnswer.class, id);
    }
    
    public static List<YstAnswer> YstAnswer.findYstAnswerEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM YstAnswer o", YstAnswer.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void YstAnswer.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void YstAnswer.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            YstAnswer attached = YstAnswer.findYstAnswer(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void YstAnswer.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void YstAnswer.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public YstAnswer YstAnswer.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        YstAnswer merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
