// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstAccount;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect YstAccount_Roo_Json {
    
    public String YstAccount.toJson() {
        return new JSONSerializer().exclude("*.class").deepSerialize(this);
    }
    
    public String YstAccount.toJson(String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").deepSerialize(this);
    }
    
    public static YstAccount YstAccount.fromJsonToYstAccount(String json) {
        return new JSONDeserializer<YstAccount>().use(null, YstAccount.class).deserialize(json);
    }
    
    public static String YstAccount.toJsonArray(Collection<YstAccount> collection) {
        return new JSONSerializer().exclude("*.class").deepSerialize(collection);
    }
    
    public static String YstAccount.toJsonArray(Collection<YstAccount> collection, String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").deepSerialize(collection);
    }
    
    public static Collection<YstAccount> YstAccount.fromJsonArrayToYstAccounts(String json) {
        return new JSONDeserializer<List<YstAccount>>().use(null, ArrayList.class).use("values", YstAccount.class).deserialize(json);
    }
    
}
