// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstAnswer;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect YstAnswer_Roo_Json {
    
    public String YstAnswer.toJson() {
        return new JSONSerializer().exclude("*.class").deepSerialize(this);
    }
    
    public String YstAnswer.toJson(String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").deepSerialize(this);
    }
    
    public static YstAnswer YstAnswer.fromJsonToYstAnswer(String json) {
        return new JSONDeserializer<YstAnswer>().use(null, YstAnswer.class).deserialize(json);
    }
    
    public static String YstAnswer.toJsonArray(Collection<YstAnswer> collection) {
        return new JSONSerializer().exclude("*.class").deepSerialize(collection);
    }
    
    public static String YstAnswer.toJsonArray(Collection<YstAnswer> collection, String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").deepSerialize(collection);
    }
    
    public static Collection<YstAnswer> YstAnswer.fromJsonArrayToYstAnswers(String json) {
        return new JSONDeserializer<List<YstAnswer>>().use(null, ArrayList.class).use("values", YstAnswer.class).deserialize(json);
    }
    
}
