// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstAnswer;
import dev.yangshengtang.domain.YstQuestion;
import dev.yangshengtang.domain.YstUser;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

privileged aspect YstAnswer_Roo_Finder {
    
    public static TypedQuery<YstAnswer> YstAnswer.findYstAnswersByQuestion(YstQuestion question) {
        if (question == null) throw new IllegalArgumentException("The question argument is required");
        EntityManager em = YstAnswer.entityManager();
        TypedQuery<YstAnswer> q = em.createQuery("SELECT o FROM YstAnswer AS o WHERE o.question = :question", YstAnswer.class);
        q.setParameter("question", question);
        return q;
    }
    
    public static TypedQuery<YstAnswer> YstAnswer.findYstAnswersByUser(YstUser user) {
        if (user == null) throw new IllegalArgumentException("The user argument is required");
        EntityManager em = YstAnswer.entityManager();
        TypedQuery<YstAnswer> q = em.createQuery("SELECT o FROM YstAnswer AS o WHERE o.user = :user", YstAnswer.class);
        q.setParameter("user", user);
        return q;
    }
    
}
