// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstAccount;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

privileged aspect YstAccount_Roo_Finder {
    
    public static TypedQuery<YstAccount> YstAccount.findYstAccountsByUsernameEquals(String username) {
        if (username == null || username.length() == 0) throw new IllegalArgumentException("The username argument is required");
        EntityManager em = YstAccount.entityManager();
        TypedQuery<YstAccount> q = em.createQuery("SELECT o FROM YstAccount AS o WHERE o.username = :username", YstAccount.class);
        q.setParameter("username", username);
        return q;
    }
    
}
