// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstCategory;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect YstCategory_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager YstCategory.entityManager;
    
    public static final EntityManager YstCategory.entityManager() {
        EntityManager em = new YstCategory().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long YstCategory.countYstCategorys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM YstCategory o", Long.class).getSingleResult();
    }
    
    public static List<YstCategory> YstCategory.findAllYstCategorys() {
        return entityManager().createQuery("SELECT o FROM YstCategory o", YstCategory.class).getResultList();
    }
    
    public static YstCategory YstCategory.findYstCategory(Integer id) {
        if (id == null) return null;
        return entityManager().find(YstCategory.class, id);
    }
    
    public static List<YstCategory> YstCategory.findYstCategoryEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM YstCategory o", YstCategory.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void YstCategory.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void YstCategory.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            YstCategory attached = YstCategory.findYstCategory(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void YstCategory.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void YstCategory.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public YstCategory YstCategory.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        YstCategory merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
