// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstCategory;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect YstCategory_Roo_Jpa_Entity {
    
    declare @type: YstCategory: @Entity;
    
    declare @type: YstCategory: @Table(name = "yst_category");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer YstCategory.id;
    
    public Integer YstCategory.getId() {
        return this.id;
    }
    
    public void YstCategory.setId(Integer id) {
        this.id = id;
    }
    
}
