// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstCategory;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect YstCategory_Roo_Configurable {
    
    declare @type: YstCategory: @Configurable;
    
}
