// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstCategory;
import dev.yangshengtang.domain.YstMedicine;
import dev.yangshengtang.domain.YstPathogenesis;
import dev.yangshengtang.domain.YstQuestion;
import dev.yangshengtang.domain.YstSymptom;
import dev.yangshengtang.domain.YstUserCategory;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

privileged aspect YstCategory_Roo_DbManaged {
    
    @OneToMany(mappedBy = "category")
    private Set<YstMedicine> YstCategory.ystMedicines;
    
    @OneToMany(mappedBy = "category")
    private Set<YstPathogenesis> YstCategory.ystPathogeneses;
    
    @OneToMany(mappedBy = "category")
    private Set<YstQuestion> YstCategory.ystQuestions;
    
    @OneToMany(mappedBy = "category")
    private Set<YstSymptom> YstCategory.ystSymptoms;
    
    @OneToMany(mappedBy = "category")
    private Set<YstUserCategory> YstCategory.ystUserCategories;
    
    @Column(name = "category", length = 45)
    @NotNull
    private String YstCategory.category;
    
    @Column(name = "describ", length = 1000)
    private String YstCategory.describ;
    
    public Set<YstMedicine> YstCategory.getYstMedicines() {
        return ystMedicines;
    }
    
    public void YstCategory.setYstMedicines(Set<YstMedicine> ystMedicines) {
        this.ystMedicines = ystMedicines;
    }
    
    public Set<YstPathogenesis> YstCategory.getYstPathogeneses() {
        return ystPathogeneses;
    }
    
    public void YstCategory.setYstPathogeneses(Set<YstPathogenesis> ystPathogeneses) {
        this.ystPathogeneses = ystPathogeneses;
    }
    
    public Set<YstQuestion> YstCategory.getYstQuestions() {
        return ystQuestions;
    }
    
    public void YstCategory.setYstQuestions(Set<YstQuestion> ystQuestions) {
        this.ystQuestions = ystQuestions;
    }
    
    public Set<YstSymptom> YstCategory.getYstSymptoms() {
        return ystSymptoms;
    }
    
    public void YstCategory.setYstSymptoms(Set<YstSymptom> ystSymptoms) {
        this.ystSymptoms = ystSymptoms;
    }
    
    public Set<YstUserCategory> YstCategory.getYstUserCategories() {
        return ystUserCategories;
    }
    
    public void YstCategory.setYstUserCategories(Set<YstUserCategory> ystUserCategories) {
        this.ystUserCategories = ystUserCategories;
    }
    
    public String YstCategory.getCategory() {
        return category;
    }
    
    public void YstCategory.setCategory(String category) {
        this.category = category;
    }
    
    public String YstCategory.getDescrib() {
        return describ;
    }
    
    public void YstCategory.setDescrib(String describ) {
        this.describ = describ;
    }
    
}
