// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstMedicine;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect YstMedicine_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager YstMedicine.entityManager;
    
    public static final EntityManager YstMedicine.entityManager() {
        EntityManager em = new YstMedicine().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long YstMedicine.countYstMedicines() {
        return entityManager().createQuery("SELECT COUNT(o) FROM YstMedicine o", Long.class).getSingleResult();
    }
    
    public static List<YstMedicine> YstMedicine.findAllYstMedicines() {
        return entityManager().createQuery("SELECT o FROM YstMedicine o", YstMedicine.class).getResultList();
    }
    
    public static YstMedicine YstMedicine.findYstMedicine(Integer id) {
        if (id == null) return null;
        return entityManager().find(YstMedicine.class, id);
    }
    
    public static List<YstMedicine> YstMedicine.findYstMedicineEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM YstMedicine o", YstMedicine.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void YstMedicine.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void YstMedicine.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            YstMedicine attached = YstMedicine.findYstMedicine(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void YstMedicine.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void YstMedicine.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public YstMedicine YstMedicine.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        YstMedicine merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
