// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstCategory;
import dev.yangshengtang.domain.YstMedicine;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

privileged aspect YstMedicine_Roo_Finder {
    
    public static TypedQuery<YstMedicine> YstMedicine.findYstMedicinesByCategory(YstCategory category) {
        if (category == null) throw new IllegalArgumentException("The category argument is required");
        EntityManager em = YstMedicine.entityManager();
        TypedQuery<YstMedicine> q = em.createQuery("SELECT o FROM YstMedicine AS o WHERE o.category = :category", YstMedicine.class);
        q.setParameter("category", category);
        return q;
    }
    
}
