// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstMedicineSymptom;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect YstMedicineSymptom_Roo_Jpa_Entity {
    
    declare @type: YstMedicineSymptom: @Entity;
    
    declare @type: YstMedicineSymptom: @Table(name = "yst_medicine_symptom");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer YstMedicineSymptom.id;
    
    public Integer YstMedicineSymptom.getId() {
        return this.id;
    }
    
    public void YstMedicineSymptom.setId(Integer id) {
        this.id = id;
    }
    
}
