// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstMedicine;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect YstMedicine_Roo_Json {
    
    public String YstMedicine.toJson() {
        return new JSONSerializer().exclude("*.class").deepSerialize(this);
    }
    
    public String YstMedicine.toJson(String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").deepSerialize(this);
    }
    
    public static YstMedicine YstMedicine.fromJsonToYstMedicine(String json) {
        return new JSONDeserializer<YstMedicine>().use(null, YstMedicine.class).deserialize(json);
    }
    
    public static String YstMedicine.toJsonArray(Collection<YstMedicine> collection) {
        return new JSONSerializer().exclude("*.class").deepSerialize(collection);
    }
    
    public static String YstMedicine.toJsonArray(Collection<YstMedicine> collection, String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").deepSerialize(collection);
    }
    
    public static Collection<YstMedicine> YstMedicine.fromJsonArrayToYstMedicines(String json) {
        return new JSONDeserializer<List<YstMedicine>>().use(null, ArrayList.class).use("values", YstMedicine.class).deserialize(json);
    }
    
}
