// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstCategory;
import dev.yangshengtang.domain.YstMedicine;
import dev.yangshengtang.domain.YstMedicineSymptom;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

privileged aspect YstMedicine_Roo_DbManaged {
    
    @OneToMany(mappedBy = "medicine")
    private Set<YstMedicineSymptom> YstMedicine.ystMedicineSymptoms;
    
    @ManyToOne
    @JoinColumn(name = "category", referencedColumnName = "id", nullable = false)
    private YstCategory YstMedicine.category;
    
    @Column(name = "medicine", length = 45)
    @NotNull
    private String YstMedicine.medicine;
    
    @Column(name = "describ", length = 1000)
    private String YstMedicine.describ;
    
    public Set<YstMedicineSymptom> YstMedicine.getYstMedicineSymptoms() {
        return ystMedicineSymptoms;
    }
    
    public void YstMedicine.setYstMedicineSymptoms(Set<YstMedicineSymptom> ystMedicineSymptoms) {
        this.ystMedicineSymptoms = ystMedicineSymptoms;
    }
    
    public YstCategory YstMedicine.getCategory() {
        return category;
    }
    
    public void YstMedicine.setCategory(YstCategory category) {
        this.category = category;
    }
    
    public String YstMedicine.getMedicine() {
        return medicine;
    }
    
    public void YstMedicine.setMedicine(String medicine) {
        this.medicine = medicine;
    }
    
    public String YstMedicine.getDescrib() {
        return describ;
    }
    
    public void YstMedicine.setDescrib(String describ) {
        this.describ = describ;
    }
    
}
