// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstMedicineSymptom;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect YstMedicineSymptom_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager YstMedicineSymptom.entityManager;
    
    public static final EntityManager YstMedicineSymptom.entityManager() {
        EntityManager em = new YstMedicineSymptom().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long YstMedicineSymptom.countYstMedicineSymptoms() {
        return entityManager().createQuery("SELECT COUNT(o) FROM YstMedicineSymptom o", Long.class).getSingleResult();
    }
    
    public static List<YstMedicineSymptom> YstMedicineSymptom.findAllYstMedicineSymptoms() {
        return entityManager().createQuery("SELECT o FROM YstMedicineSymptom o", YstMedicineSymptom.class).getResultList();
    }
    
    public static YstMedicineSymptom YstMedicineSymptom.findYstMedicineSymptom(Integer id) {
        if (id == null) return null;
        return entityManager().find(YstMedicineSymptom.class, id);
    }
    
    public static List<YstMedicineSymptom> YstMedicineSymptom.findYstMedicineSymptomEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM YstMedicineSymptom o", YstMedicineSymptom.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void YstMedicineSymptom.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void YstMedicineSymptom.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            YstMedicineSymptom attached = YstMedicineSymptom.findYstMedicineSymptom(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void YstMedicineSymptom.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void YstMedicineSymptom.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public YstMedicineSymptom YstMedicineSymptom.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        YstMedicineSymptom merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
