// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstMedicineSymptom;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect YstMedicineSymptom_Roo_Json {
    
    public String YstMedicineSymptom.toJson() {
        return new JSONSerializer().exclude("*.class").deepSerialize(this);
    }
    
    public String YstMedicineSymptom.toJson(String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").deepSerialize(this);
    }
    
    public static YstMedicineSymptom YstMedicineSymptom.fromJsonToYstMedicineSymptom(String json) {
        return new JSONDeserializer<YstMedicineSymptom>().use(null, YstMedicineSymptom.class).deserialize(json);
    }
    
    public static String YstMedicineSymptom.toJsonArray(Collection<YstMedicineSymptom> collection) {
        return new JSONSerializer().exclude("*.class").deepSerialize(collection);
    }
    
    public static String YstMedicineSymptom.toJsonArray(Collection<YstMedicineSymptom> collection, String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").deepSerialize(collection);
    }
    
    public static Collection<YstMedicineSymptom> YstMedicineSymptom.fromJsonArrayToYstMedicineSymptoms(String json) {
        return new JSONDeserializer<List<YstMedicineSymptom>>().use(null, ArrayList.class).use("values", YstMedicineSymptom.class).deserialize(json);
    }
    
}
