// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstCategory;
import dev.yangshengtang.domain.YstPathogenesis;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

privileged aspect YstPathogenesis_Roo_DbManaged {
    
    @ManyToOne
    @JoinColumn(name = "category", referencedColumnName = "id", nullable = false)
    private YstCategory YstPathogenesis.category;
    
    @Column(name = "pathogenesis", length = 500)
    @NotNull
    private String YstPathogenesis.pathogenesis;
    
    @Column(name = "describ", length = 1000)
    private String YstPathogenesis.describ;
    
    public YstCategory YstPathogenesis.getCategory() {
        return category;
    }
    
    public void YstPathogenesis.setCategory(YstCategory category) {
        this.category = category;
    }
    
    public String YstPathogenesis.getPathogenesis() {
        return pathogenesis;
    }
    
    public void YstPathogenesis.setPathogenesis(String pathogenesis) {
        this.pathogenesis = pathogenesis;
    }
    
    public String YstPathogenesis.getDescrib() {
        return describ;
    }
    
    public void YstPathogenesis.setDescrib(String describ) {
        this.describ = describ;
    }
    
}
