// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstCategory;
import dev.yangshengtang.domain.YstPathogenesis;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

privileged aspect YstPathogenesis_Roo_Finder {
    
    public static TypedQuery<YstPathogenesis> YstPathogenesis.findYstPathogenesesByCategory(YstCategory category) {
        if (category == null) throw new IllegalArgumentException("The category argument is required");
        EntityManager em = YstPathogenesis.entityManager();
        TypedQuery<YstPathogenesis> q = em.createQuery("SELECT o FROM YstPathogenesis AS o WHERE o.category = :category", YstPathogenesis.class);
        q.setParameter("category", category);
        return q;
    }
    
}
