// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstPathogenesis;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect YstPathogenesis_Roo_Json {
    
    public String YstPathogenesis.toJson() {
        return new JSONSerializer().exclude("*.class").deepSerialize(this);
    }
    
    public String YstPathogenesis.toJson(String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").deepSerialize(this);
    }
    
    public static YstPathogenesis YstPathogenesis.fromJsonToYstPathogenesis(String json) {
        return new JSONDeserializer<YstPathogenesis>().use(null, YstPathogenesis.class).deserialize(json);
    }
    
    public static String YstPathogenesis.toJsonArray(Collection<YstPathogenesis> collection) {
        return new JSONSerializer().exclude("*.class").deepSerialize(collection);
    }
    
    public static String YstPathogenesis.toJsonArray(Collection<YstPathogenesis> collection, String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").deepSerialize(collection);
    }
    
    public static Collection<YstPathogenesis> YstPathogenesis.fromJsonArrayToYstPathogeneses(String json) {
        return new JSONDeserializer<List<YstPathogenesis>>().use(null, ArrayList.class).use("values", YstPathogenesis.class).deserialize(json);
    }
    
}
