// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstPathogenesis;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect YstPathogenesis_Roo_Jpa_Entity {
    
    declare @type: YstPathogenesis: @Entity;
    
    declare @type: YstPathogenesis: @Table(name = "yst_pathogenesis");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer YstPathogenesis.id;
    
    public Integer YstPathogenesis.getId() {
        return this.id;
    }
    
    public void YstPathogenesis.setId(Integer id) {
        this.id = id;
    }
    
}
