// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstPathogenesis;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect YstPathogenesis_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager YstPathogenesis.entityManager;
    
    public static final EntityManager YstPathogenesis.entityManager() {
        EntityManager em = new YstPathogenesis().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long YstPathogenesis.countYstPathogeneses() {
        return entityManager().createQuery("SELECT COUNT(o) FROM YstPathogenesis o", Long.class).getSingleResult();
    }
    
    public static List<YstPathogenesis> YstPathogenesis.findAllYstPathogeneses() {
        return entityManager().createQuery("SELECT o FROM YstPathogenesis o", YstPathogenesis.class).getResultList();
    }
    
    public static YstPathogenesis YstPathogenesis.findYstPathogenesis(Integer id) {
        if (id == null) return null;
        return entityManager().find(YstPathogenesis.class, id);
    }
    
    public static List<YstPathogenesis> YstPathogenesis.findYstPathogenesisEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM YstPathogenesis o", YstPathogenesis.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void YstPathogenesis.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void YstPathogenesis.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            YstPathogenesis attached = YstPathogenesis.findYstPathogenesis(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void YstPathogenesis.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void YstPathogenesis.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public YstPathogenesis YstPathogenesis.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        YstPathogenesis merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
