// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstCategory;
import dev.yangshengtang.domain.YstQuestion;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

privileged aspect YstQuestion_Roo_Finder {
    
    public static TypedQuery<YstQuestion> YstQuestion.findYstQuestionsByCategory(YstCategory category) {
        if (category == null) throw new IllegalArgumentException("The category argument is required");
        EntityManager em = YstQuestion.entityManager();
        TypedQuery<YstQuestion> q = em.createQuery("SELECT o FROM YstQuestion AS o WHERE o.category = :category", YstQuestion.class);
        q.setParameter("category", category);
        return q;
    }
    
}
