// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstQuestion;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect YstQuestion_Roo_Jpa_Entity {
    
    declare @type: YstQuestion: @Entity;
    
    declare @type: YstQuestion: @Table(name = "yst_question");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer YstQuestion.id;
    
    public Integer YstQuestion.getId() {
        return this.id;
    }
    
    public void YstQuestion.setId(Integer id) {
        this.id = id;
    }
    
}
