// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstQuestion;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect YstQuestion_Roo_Json {
    
    public String YstQuestion.toJson() {
        return new JSONSerializer().exclude("*.class").deepSerialize(this);
    }
    
    public String YstQuestion.toJson(String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").deepSerialize(this);
    }
    
    public static YstQuestion YstQuestion.fromJsonToYstQuestion(String json) {
        return new JSONDeserializer<YstQuestion>().use(null, YstQuestion.class).deserialize(json);
    }
    
    public static String YstQuestion.toJsonArray(Collection<YstQuestion> collection) {
        return new JSONSerializer().exclude("*.class").deepSerialize(collection);
    }
    
    public static String YstQuestion.toJsonArray(Collection<YstQuestion> collection, String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").deepSerialize(collection);
    }
    
    public static Collection<YstQuestion> YstQuestion.fromJsonArrayToYstQuestions(String json) {
        return new JSONDeserializer<List<YstQuestion>>().use(null, ArrayList.class).use("values", YstQuestion.class).deserialize(json);
    }
    
}
