// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstSymptom;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect YstSymptom_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager YstSymptom.entityManager;
    
    public static final EntityManager YstSymptom.entityManager() {
        EntityManager em = new YstSymptom().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long YstSymptom.countYstSymptoms() {
        return entityManager().createQuery("SELECT COUNT(o) FROM YstSymptom o", Long.class).getSingleResult();
    }
    
    public static List<YstSymptom> YstSymptom.findAllYstSymptoms() {
        return entityManager().createQuery("SELECT o FROM YstSymptom o", YstSymptom.class).getResultList();
    }
    
    public static YstSymptom YstSymptom.findYstSymptom(Integer id) {
        if (id == null) return null;
        return entityManager().find(YstSymptom.class, id);
    }
    
    public static List<YstSymptom> YstSymptom.findYstSymptomEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM YstSymptom o", YstSymptom.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void YstSymptom.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void YstSymptom.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            YstSymptom attached = YstSymptom.findYstSymptom(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void YstSymptom.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void YstSymptom.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public YstSymptom YstSymptom.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        YstSymptom merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
