// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstSymptom;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect YstSymptom_Roo_Configurable {
    
    declare @type: YstSymptom: @Configurable;
    
}
