// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstCategory;
import dev.yangshengtang.domain.YstSymptom;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

privileged aspect YstSymptom_Roo_Finder {
    
    public static TypedQuery<YstSymptom> YstSymptom.findYstSymptomsByCategory(YstCategory category) {
        if (category == null) throw new IllegalArgumentException("The category argument is required");
        EntityManager em = YstSymptom.entityManager();
        TypedQuery<YstSymptom> q = em.createQuery("SELECT o FROM YstSymptom AS o WHERE o.category = :category", YstSymptom.class);
        q.setParameter("category", category);
        return q;
    }
    
}
