// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstCategory;
import dev.yangshengtang.domain.YstMedicineSymptom;
import dev.yangshengtang.domain.YstSymptom;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

privileged aspect YstSymptom_Roo_DbManaged {
    
    @OneToMany(mappedBy = "symptomcol")
    private Set<YstMedicineSymptom> YstSymptom.ystMedicineSymptoms;
    
    @ManyToOne
    @JoinColumn(name = "category", referencedColumnName = "id", nullable = false)
    private YstCategory YstSymptom.category;
    
    @Column(name = "symptom", length = 500)
    @NotNull
    private String YstSymptom.symptom;
    
    @Column(name = "describ", length = 1000)
    private String YstSymptom.describ;
    
    public Set<YstMedicineSymptom> YstSymptom.getYstMedicineSymptoms() {
        return ystMedicineSymptoms;
    }
    
    public void YstSymptom.setYstMedicineSymptoms(Set<YstMedicineSymptom> ystMedicineSymptoms) {
        this.ystMedicineSymptoms = ystMedicineSymptoms;
    }
    
    public YstCategory YstSymptom.getCategory() {
        return category;
    }
    
    public void YstSymptom.setCategory(YstCategory category) {
        this.category = category;
    }
    
    public String YstSymptom.getSymptom() {
        return symptom;
    }
    
    public void YstSymptom.setSymptom(String symptom) {
        this.symptom = symptom;
    }
    
    public String YstSymptom.getDescrib() {
        return describ;
    }
    
    public void YstSymptom.setDescrib(String describ) {
        this.describ = describ;
    }
    
}
