// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstCategory;
import dev.yangshengtang.domain.YstUser;
import dev.yangshengtang.domain.YstUserCategory;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

privileged aspect YstUserCategory_Roo_DbManaged {
    
    @ManyToOne
    @JoinColumn(name = "category", referencedColumnName = "id", nullable = false)
    private YstCategory YstUserCategory.category;
    
    @ManyToOne
    @JoinColumn(name = "user", referencedColumnName = "id", nullable = false)
    private YstUser YstUserCategory.user;
    
    @Column(name = "tendency")
    private Boolean YstUserCategory.tendency;
    
    public YstCategory YstUserCategory.getCategory() {
        return category;
    }
    
    public void YstUserCategory.setCategory(YstCategory category) {
        this.category = category;
    }
    
    public YstUser YstUserCategory.getUser() {
        return user;
    }
    
    public void YstUserCategory.setUser(YstUser user) {
        this.user = user;
    }
    
    public Boolean YstUserCategory.getTendency() {
        return tendency;
    }
    
    public void YstUserCategory.setTendency(Boolean tendency) {
        this.tendency = tendency;
    }
    
}
