// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstUserCategory;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect YstUserCategory_Roo_Json {
    
    public String YstUserCategory.toJson() {
        return new JSONSerializer().exclude("*.class").deepSerialize(this);
    }
    
    public String YstUserCategory.toJson(String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").deepSerialize(this);
    }
    
    public static YstUserCategory YstUserCategory.fromJsonToYstUserCategory(String json) {
        return new JSONDeserializer<YstUserCategory>().use(null, YstUserCategory.class).deserialize(json);
    }
    
    public static String YstUserCategory.toJsonArray(Collection<YstUserCategory> collection) {
        return new JSONSerializer().exclude("*.class").deepSerialize(collection);
    }
    
    public static String YstUserCategory.toJsonArray(Collection<YstUserCategory> collection, String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").deepSerialize(collection);
    }
    
    public static Collection<YstUserCategory> YstUserCategory.fromJsonArrayToYstUserCategorys(String json) {
        return new JSONDeserializer<List<YstUserCategory>>().use(null, ArrayList.class).use("values", YstUserCategory.class).deserialize(json);
    }
    
}
