// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dev.yangshengtang.domain;

import dev.yangshengtang.domain.YstUser;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect YstUser_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager YstUser.entityManager;
    
    public static final EntityManager YstUser.entityManager() {
        EntityManager em = new YstUser().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long YstUser.countYstUsers() {
        return entityManager().createQuery("SELECT COUNT(o) FROM YstUser o", Long.class).getSingleResult();
    }
    
    public static List<YstUser> YstUser.findAllYstUsers() {
        return entityManager().createQuery("SELECT o FROM YstUser o", YstUser.class).getResultList();
    }
    
    public static YstUser YstUser.findYstUser(Integer id) {
        if (id == null) return null;
        return entityManager().find(YstUser.class, id);
    }
    
    public static List<YstUser> YstUser.findYstUserEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM YstUser o", YstUser.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void YstUser.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void YstUser.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            YstUser attached = YstUser.findYstUser(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void YstUser.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void YstUser.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public YstUser YstUser.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        YstUser merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
